// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"geektime/webook/interactive/events"
	"geektime/webook/interactive/grpc"
	"geektime/webook/interactive/ioc"
	"geektime/webook/interactive/repository"
	"geektime/webook/interactive/repository/cache"
	"geektime/webook/interactive/repository/dao"
	"geektime/webook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	srcDB := ioc.InitSrcDB()
	dstDB := ioc.InitDstDB()
	loggerV1 := ioc.InitLoggerV1()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB, loggerV1)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewInteractiveRedisCache(cmdable)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, loggerV1, interactiveCache)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(interactiveServiceServer, client, loggerV1)
	saramaClient := ioc.InitKafkaClient()
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(interactiveRepository, saramaClient, loggerV1)
	consumer := ioc.InitFixerConsumer(saramaClient, loggerV1, srcDB, dstDB)
	v := ioc.InitConsumers(interactiveReadEventConsumer, consumer)
	syncProducer := ioc.InitSyncProducer(saramaClient)
	producer := ioc.InitInteractiveProducer(syncProducer)
	ginxServer := ioc.InitMigratorWebServer(loggerV1, srcDB, dstDB, doubleWritePool, producer)
	app := &App{
		server:    server,
		consumers: v,
		webAdmin:  ginxServer,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitRedis, ioc.InitDstDB, ioc.InitSrcDB, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitKafkaClient, ioc.InitSyncProducer, ioc.InitLoggerV1)

var interactiveSvcSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewInteractiveRedisCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

// 不停机数据迁移后台管理服务端
// 源目数据库进行校验，pool进行双写
var migratorProvider = wire.NewSet(ioc.InitInteractiveProducer, ioc.InitMigratorWebServer, ioc.InitFixerConsumer)
