apiVersion: v1
#声明 k8s 有哪些 volume
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    app: my-local-pv
spec:
  storageClassName: suibian
  capacity:
    storage: 1Gi
  #支持的读写方式
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

