test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webook_intr"

kafka:
  addr: "localhost:9094"

grpc:
  server:
    port: 8090
    etcdAddrs:
      - "localhost:12379"
    name: "interactive"
migrator:
  http:
    addr: ":8082"

