test:
  key: value1234

redis:
  addr: "localhost:6379"

db:
  dsn: "root:root@tcp(localhost:13316)/webook"

kafka:
  addr:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"

grpc:
  client:
    intr:
      addr: "etcd:///service/interactive"
      secure: false
#流量控制客户端
#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      secure: false
#      threshold: 50